[build]
builder = "nixpacks"

[deploy]
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
PORT = "$PORT"

[healthcheck]
path = "/health"
interval = 30
timeout = 10