[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production"
PORT = "$PORT"

[healthcheck]
path = "/health"
interval = 30
timeout = 10