services:
  - type: web
    name: meart
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MODEL_DIR
        value: /tmp/u2net
      - key: PORT
        value: 9000