services:
  - type: web
    name: meart-e
    env: node
    buildCommand: npm ci --omit=dev --prefer-offline --no-audit --no-fund --loglevel=error --progress=false && npm run build
    startCommand: npm run start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    buildFilter:
      paths:
        - "*.js"
        - "*.json"
        - "*.mjs"
        - "public/**"
        - "scripts/**"
      ignorePaths:
        - "node_modules/**"
        - ".git/**"
        - "*.md"
        - ".render-build-cache-clear"