services:
  - type: web
    name: meart
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start:with-wait
    envVars:
      - key: NODE_ENV
        value: production
      - key: MODEL_DIR
        value: /tmp/u2net
      - key: PORT
        value: 9000
    healthCheckPath: /health
    autoDeploy: true