services:
  - type: web
    name: meart-e
    env: node
    plan: starter
    region: singapore
    repo: https://github.com/sim6404/MeArt_E
    branch: main
    buildCommand: npm ci --omit=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: AI_PROVIDER
        value: none